name: basicnumericalmethods
version: '3.0.9'
summary: basic_numerical_methods app
description: This is a basic_numerical_methods app demo
type: base
build-base: core20
grade: stable 
confinement: strict 

apps:
  basicnumericalmethods:
    command: basic_numerical_methods
    plugs: [home, x11, wayland, opengl]

parts:
  application:
    plugin: qmake
    override-build: |
      install-d $SNAPCRAFT _part_install/opt/basicnumericalmethods
      INSTALL basic_numerical_methods $SNAPCRAFT _part_install/opt/basicnumericalmethods/basic_numerical_methods
    after: [desktop-qt5]
    
  desktop-qt5:
    plugin: nil
    build-packages:
        - pkg-config
        - qt5-default
        - qt5-qmake
        - qtbase5-dev
    stage-packages:
        - libqt5core5a
        - libqt5gui5
        - libqt5widgets5
